# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickSample' do

  use_frameworks!

  def testing_pods
    pod 'Quick'
    pod 'Nimble'
  end

  target 'QuickSampleTests' do
    testing_pods
  end

  target 'QuickSampleUITests' do
    testing_pods
  end

end
