# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
])

languages([
    'ja-JP'
])

concurrent_simulators(true)

scheme("QuickSample")

output_directory("./screenshots")

clear_previous_screenshots(true)

